public enum Sigils {//Need to make an encoder / decoder for this 
    PlayedFromHand,
    //im sorry^^ this is pretty hacky

    Rabbit,
    Bees,
    Sprinter,
    DeathTouch,
    Fledgling,
    Dam,
    Hoarder,
    Burrower,
    Fecundity,
    LooseTail,
    CorpseEater,
    BoneKing,
    Waterborne,
    Unkillable,
    SharpQuills,
    Hefty,
    AntSpawner,
    Guardian,
    Airborne,
    ManyLives,
    Repulsive,
    WorthySacrifice,
    MightyLeap,
    BifurcatedStrike,
    TrifurcatedStrike,
    FrozenAway,
    TrinketBearer,
    SteelTrap,
    Amorphous,
    TidalLock,
    OmniStrike,
    Leader,
    Bellist,
    Stinky

}